/*
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package io.elepay.api

// 返金のサマリー。複数回返金された場合、返金内容をサマリーして返します。
type RefundExtDto struct {
	// 対象種類の表記
	Object string `json:"object,omitempty"`
	// 返金総額
	Amount int32 `json:"amount,omitempty"`
	// 返金回数
	TotalCount int32 `json:"totalCount,omitempty"`
	// 返金詳細情報
	Data []RefundDto `json:"data,omitempty"`
}
