/*
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package io.elepay.api

// 支払リクエスト
type ChargeReq struct {
	// 金額
	Amount int32 `json:"amount,omitempty"`
	// 通貨コード (ISO_4217)
	Currency string `json:"currency,omitempty"`
	PaymentMethod PaymentMethodType `json:"paymentMethod,omitempty"`
	// お客様側のシステムオーダーNo（例：注文番号、決済IDなど）
	OrderNo string `json:"orderNo,omitempty"`
	// 決済に関する説明
	Description string `json:"description,omitempty"`
	// 決済に関する追加情報がある場合に利用します。
	Extra map[string]map[string]interface{} `json:"extra,omitempty"`
	// メタデータ
	Metadata map[string]map[string]interface{} `json:"metadata,omitempty"`
	// Client IP アドレス
	ClientIp string `json:"clientIp,omitempty"`
}
