/*
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package io.elepay.api
// PaymentMethodType : 決済方法 - alipay - alipay_web - applepay - applepay_cn - applepay_cn_web - creditcard - googlepay - paypal - unionpay - unionpay_web - linepay - linepay_web - wechat - wechat_qr - paidy - paypay - alipay_qr 
type PaymentMethodType string

// List of PaymentMethodType
const (
	ALIPAY PaymentMethodType = "alipay"
	ALIPAY_WEB PaymentMethodType = "alipay_web"
	APPLEPAY PaymentMethodType = "applepay"
	APPLEPAY_WEB PaymentMethodType = "applepay_web"
	APPLEPAY_CN PaymentMethodType = "applepay_cn"
	APPLEPAY_CN_WEB PaymentMethodType = "applepay_cn_web"
	CREDITCARD PaymentMethodType = "creditcard"
	GOOGLEPAY PaymentMethodType = "googlepay"
	PAYPAL PaymentMethodType = "paypal"
	UNIONPAY PaymentMethodType = "unionpay"
	UNIONPAY_WEB PaymentMethodType = "unionpay_web"
	LINEPAY_WEB PaymentMethodType = "linepay_web"
	LINEPAY PaymentMethodType = "linepay"
	WECHAT PaymentMethodType = "wechat"
	WECHAT_QR PaymentMethodType = "wechat_qr"
	PAIDY PaymentMethodType = "paidy"
	PAYPAY PaymentMethodType = "paypay"
	ALIPAY_QR PaymentMethodType = "alipay_qr"
)