/*
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package io.elepay.api

// 支払いオブジェクト
type ChargeDto struct {
	// Charge ID
	Id string `json:"id,omitempty"`
	// 対象種類の表記
	Object string `json:"object,omitempty"`
	// 本番モードかどうか - false テストモード - true 本番モード 
	LiveMode bool `json:"liveMode,omitempty"`
	// 支払い金額
	Amount int32 `json:"amount,omitempty"`
	// 通貨コード (ISO_4217)
	Currency string `json:"currency,omitempty"`
	PaymentMethod PaymentMethodType `json:"paymentMethod,omitempty"`
	// お客様システム側のオーダーNo、例えば注文番号、決済IDなど
	OrderNo string `json:"orderNo,omitempty"`
	// 支払い説明文
	Description string `json:"description,omitempty"`
	// 支払いエキストラデータ
	Extra map[string]map[string]interface{} `json:"extra,omitempty"`
	// 支払いメタデータ
	Metadata map[string]map[string]interface{} `json:"metadata,omitempty"`
	// Client IP アドレス
	ClientIp string `json:"clientIp,omitempty"`
	// 支払い済みフラグ
	Paid bool `json:"paid,omitempty"`
	// 返金済みフラグ
	Refunded bool `json:"refunded,omitempty"`
	Refunds RefundExtDto `json:"refunds,omitempty"`
	// 支払い状態
	Status string `json:"status,omitempty"`
	// Client SDK の認証情報
	Credential string `json:"credential,omitempty"`
	// 支払い時間のUTCタイムスタンプ
	PaidTime int64 `json:"paidTime,omitempty"`
	// 返金時間のUTCタイムスタンプ
	RefundTime int64 `json:"refundTime,omitempty"`
	// 支払い請求有効時間のUTCタイムスタンプ
	ExpiryTime int64 `json:"expiryTime,omitempty"`
	// 支払い締め時間のUTCタイムスタンプ
	SettleTime int64 `json:"settleTime,omitempty"`
	// 支払い新規時間のUTCタイムスタンプ
	CreateTime int64 `json:"createTime,omitempty"`
}
