/*
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package io.elepay.api
// ChargeDateTimeType : 時間項目 - expiry_time 支払有効時間 - paid_time 払う時間 - settle_time 支払締め時間 - create_time 支払新規時間 - update_time 支払更新時間 
type ChargeDateTimeType string

// List of ChargeDateTimeType
const (
	EXPIRY_TIME ChargeDateTimeType = "expiry_time"
	PAID_TIME ChargeDateTimeType = "paid_time"
	SETTLE_TIME ChargeDateTimeType = "settle_time"
	CREATE_TIME ChargeDateTimeType = "create_time"
	UPDATE_TIME ChargeDateTimeType = "update_time"
)