/*
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package io.elepay.api

// 返金リクエスト
type RefundReq struct {
	// Charge ID
	ChargeId string `json:"chargeId,omitempty"`
	// 返金額。全額返金、及び amount の指定で任意の金額で返金ができます。
	Amount int32 `json:"amount,omitempty"`
	// 通貨コード (ISO_4217)
	Currency string `json:"currency,omitempty"`
	// 返金理由
	Reason string `json:"reason,omitempty"`
}
