/*
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package io.elepay.api

// 返金オブジェクト
type RefundDto struct {
	// Refund ID
	Id string `json:"id,omitempty"`
	// 対象種類の表記
	Object string `json:"object,omitempty"`
	// Charge ID
	ChargeId string `json:"chargeId,omitempty"`
	// 本番モードかどうか - false テストモード - true 本番モード 
	LiveMode bool `json:"liveMode,omitempty"`
	// 返金金額。全額返金、及び amount を指定することで金額の部分返金を行うことができます。
	Amount int32 `json:"amount,omitempty"`
	// 通貨コード (ISO_4217)
	Currency string `json:"currency,omitempty"`
	// 返金理由
	Reason string `json:"reason,omitempty"`
	// 返金状態
	Status string `json:"status,omitempty"`
	// 返金を行う時間のUTCタイムスタンプ。
	RefundedTime int64 `json:"refundedTime,omitempty"`
	// 返金新規時間のUTCタイムスタンプ。
	CreateTime int64 `json:"createTime,omitempty"`
}
